# Практическое задание № 3

**Задание:** Осуществите сбор данных по товарам. 

- **Шаг 1.** Импортируйте библиотеки. Подключите источник данных http://books.toscrape.com/catalogue/page-1.html

- **Шаг 2.** С помощью библиотеки BeautifulSoup найдите HTML теги, в которых находится информация по товарам (Название книги, цена).  
    * Алгоритм парсинга используйте html.parser.
    * Извлечь данные из 5ти страниц 

- **Шаг 3.** Выведите результат в DataFarme (пример в таблице): 

Название книги | цена 
--|--
A Light in the ...	| £51.77
Tipping the Velvet	| £53.74
Soumission	| £50.10
Sharp Objects	| £47.82

- **Шаг 4.** Сохраните DataFarme в файл csv.

- **Шаг 5.** Опубликуйте файл ipynb с решением данного задания, прикрепив его в этом задании на платформу Один.

In [3]:
#Шаг 1. Импортируйте библиотеки. Подключите источник данных http://books.toscrape.com/catalogue/page-1.html
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import datetime as dt 
import csv
import re
import string
url = 'http://books.toscrape.com/catalogue/page-1.html'

In [4]:
#Шаг 2. С помощью библиотеки BeautifulSoup найдите HTML теги, в которых находится информация по товарам (Название книги, цена).
#Алгоритм парсинга используйте html.parser.
#Извлечь данные из 5ти страниц
product = list() #сюда будем записывать товары

tek_page = 1
pages = 3 # задаем число больше номера первой страницы, для старта цикла

while tek_page <= 5:
    newUrl = url.replace('1', str(tek_page))
    response = requests.get(newUrl)
    soup = BeautifulSoup(response.text, 'html.parser')
    items = soup.find_all('li', {'class':'col-xs-6 col-sm-4 col-md-3 col-lg-3'})
    for n, i in enumerate(items):
       # name = i.find('h3').get_text().strip()
       # print(f'{n}. {name}')
        name = i.find('h3').get_text().strip()
        price = i.find('p', {'class':'price_color'}).get_text().strip()[1:]
        product.append(
            {'name' : name,
             'price' : price
            }) 
        print(f'{name} стоимость:  {price}') 
    tek_page +=1

A Light in the ... стоимость:  £51.77
Tipping the Velvet стоимость:  £53.74
Soumission стоимость:  £50.10
Sharp Objects стоимость:  £47.82
Sapiens: A Brief History ... стоимость:  £54.23
The Requiem Red стоимость:  £22.65
The Dirty Little Secrets ... стоимость:  £33.34
The Coming Woman: A ... стоимость:  £17.93
The Boys in the ... стоимость:  £22.60
The Black Maria стоимость:  £52.15
Starving Hearts (Triangular Trade ... стоимость:  £13.99
Shakespeare's Sonnets стоимость:  £20.66
Set Me Free стоимость:  £17.46
Scott Pilgrim's Precious Little ... стоимость:  £52.29
Rip it Up and ... стоимость:  £35.02
Our Band Could Be ... стоимость:  £57.25
Olio стоимость:  £23.88
Mesaerion: The Best Science ... стоимость:  £37.59
Libertarianism for Beginners стоимость:  £51.33
It's Only the Himalayas стоимость:  £45.17
In Her Wake стоимость:  £12.84
How Music Works стоимость:  £37.32
Foolproof Preserving: A Guide ... стоимость:  £30.52
Chase Me (Paris Nights ... стоимость:  £25.27
Black Dust стоимость:  £34.53
Birdsong: A Story in ... стоимость:  £54.64
America's Cradle of Quarterbacks: ... стоимость:  £22.50
Aladdin and His Wonderful ... стоимость:  £53.13
Worlds Elsewhere: Journeys Around ... стоимость:  £40.30
Wall and Piece стоимость:  £44.18
The Four Agreements: A ... стоимость:  £17.66
The Five Love Languages: ... стоимость:  £31.05
The Elephant Tree стоимость:  £23.82
The Bear and the ... стоимость:  £36.89
Sophie's World стоимость:  £15.94
Penny Maybe стоимость:  £33.29
Maude (1883-1993):She Grew Up ... стоимость:  £18.02
In a Dark, Dark ... стоимость:  £19.63
Behind Closed Doors стоимость:  £52.22
You can't bury them ... стоимость:  £33.63
Slow States of Collapse: ... стоимость:  £57.31
Reasons to Stay Alive стоимость:  £26.41
Private Paris (Private #10) стоимость:  £47.61
#HigherSelfie: Wake Up Your ... стоимость:  £23.11
Without Borders (Wanderlove #1) стоимость:  £45.07
When We Collided стоимость:  £31.77
We Love You, Charlie ... стоимость:  £50.27
Untitled Collection: Sabbath Poems ... стоимость:  £14.27
Unseen City: The Majesty ... стоимость:  £44.18
Unicorn Tracks стоимость:  £18.78
Unbound: How Eight Technologies ... стоимость:  £25.52
Tsubasa: WoRLD CHRoNiCLE 2 ... стоимость:  £16.28
Throwing Rocks at the ... стоимость:  £31.12
This One Summer стоимость:  £19.49
Thirst стоимость:  £17.27
The Torch Is Passed: ... стоимость:  £19.09
The Secret of Dreadwillow ... стоимость:  £56.13
The Pioneer Woman Cooks: ... стоимость:  £56.41
The Past Never Ends стоимость:  £56.50
The Natural History of ... стоимость:  £45.22
The Nameless City (The ... стоимость:  £38.16
The Murder That Never ... стоимость:  £54.11
The Most Perfect Thing: ... стоимость:  £42.96
The Mindfulness and Acceptance ... стоимость:  £23.89
The Life-Changing Magic of ... стоимость:  £16.77
The Inefficiency Assassin: Time ... стоимость:  £20.59
The Gutsy Girl: Escapades ... стоимость:  £37.13
The Electric Pencil: Drawings ... стоимость:  £56.06
The Death of Humanity: ... стоимость:  £58.11
The Bulletproof Diet: Lose ... стоимость:  £49.05
The Art Forger стоимость:  £40.76
The Age of Genius: ... стоимость:  £19.73
The Activist's Tao Te ... стоимость:  £32.24
Spark Joy: An Illustrated ... стоимость:  £41.83
Soul Reader стоимость:  £39.58
Security стоимость:  £39.25
Saga, Volume 6 (Saga ... стоимость:  £25.02
Saga, Volume 5 (Saga ... стоимость:  £51.04
Reskilling America: Learning to ... стоимость:  £19.83
Rat Queens, Vol. 3: ... стоимость:  £50.40
Princess Jellyfish 2-in-1 Omnibus, ... стоимость:  £13.61
Princess Between Worlds (Wide-Awake ... стоимость:  £13.34
Pop Gun War, Volume ... стоимость:  £18.97
Political Suicide: Missteps, Peccadilloes, ... стоимость:  £36.28
Patience стоимость:  £10.16
Outcast, Vol. 1: A ... стоимость:  £15.44
orange: The Complete Collection ... стоимость:  £48.41
Online Marketing for Busy ... стоимость:  £46.35
On a Midnight Clear стоимость:  £14.07
Obsidian (Lux #1) стоимость:  £14.86
My Paris Kitchen: Recipes ... стоимость:  £33.37
Masks and Shadows стоимость:  £56.40
Mama Tried: Traditional Italian ... стоимость:  £14.02
Lumberjanes, Vol. 2: Friendship ... стоимость:  £46.91
Lumberjanes, Vol. 1: Beware ... стоимость:  £45.61
Lumberjanes Vol. 3: A ... стоимость:  £19.92
Layered: Baking, Building, and ... стоимость:  £40.11
Judo: Seven Steps to ... стоимость:  £53.90
Join стоимость:  £35.67
In the Country We ... стоимость:  £22.00

In [5]:
#Шаг 3. Выведите результат в DataFarme
df = pd.DataFrame(product)
df.head()

                           name   price
0            A Light in the ...  £51.77
1            Tipping the Velvet  £53.74
2                    Soumission  £50.10
3                 Sharp Objects  £47.82
4  Sapiens: A Brief History ...  £54.23

In [6]:
#Шаг 4. Сохраните DataFarme в файл csv.
df.to_csv('booklist.csv')